### PR TITLE
minor fixes: moving a formula and updating outdated references

### PR DESCRIPTION
**Pull request by mr-threepwood**
The placement of the formula at the beginning of chapter 12.1. seems a little off for me in regard to ending the first paragraph by _"As you might remember from school this is simply:"_ and being immediately followed by the next paragraph.

magnitude_old

I would suggest moving the formula up accordingly.

magnitude_new

### CODE REVIEW

**Comment by mr-threepwood** [comment]
Added a quick fix for failing instruction `cargo run --bin magnitude` in analogy to pull request #6.

**Comment by mr-threepwood** [comment]
Updated an outdated reference in the section _explore_ referring to the snake game which had become chapter 14 in this edition of the book.

I apologize for the many commits here in this PR and even force pushing after doing a rebase to squash silly "fixes of the fix" as I hit commit too soon and too often before setting up the link to the snake game chapter correctly. :sweat:

**Comment by mr-threepwood** [comment]
Found and updated another reference in `explore.md` to match the current chapter numbers.

**Comment by mr-threepwood** [comment]
One more oudated reference name found in _appendix/3-mag-calibration_ and updated.

**Comment by BartMassey** [comment]
Thank you for these! Apologies for the slow response: was out of country last week.

**Pull request merged**
